# Generated by Django 3.2.5 on 2021-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kudos',
            name='message',
            field=models.CharField(default='', max_length=100),
        ),
    ]
