# Generated by Django 3.2.5 on 2021-07-17 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0002_kudos_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kudos',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
