# Generated by Django 3.2.5 on 2021-07-18 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kudos', '0003_alter_kudos_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='prize',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
